#server:
#  port: 8888
#spring:
#  application:
#    name: register
#  profiles:
#    active: dev
#eureka:
#  server:
#    #开启自我保护
#    enable-self-preservation: true
#  instance:
#    #以IP地址注册
#    preferIpAddress: true
#    hostname: ${HOST_NAME}
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
