management:
    endpoints:
        web:
            exposure:
                include: bus-refresh
spring:
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest